"""
Django settings for CityRunner project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote, unquote, urlparse, urlunparse

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-dsd%03$1&g)wi$tl4rk*6(mj1rnixnkq^w@#letle@dkx&4isy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.vercel.app', '.now.sh']

VERCEL_URL = (os.environ.get('VERCEL_URL') or '').strip().replace('https://', '').replace('http://', '')
if VERCEL_URL:
    ALLOWED_HOSTS.append(VERCEL_URL)
    CSRF_TRUSTED_ORIGINS = [f'https://{VERCEL_URL}', f'http://{VERCEL_URL}']
else:
    CSRF_TRUSTED_ORIGINS = []

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = 'Lax'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corridas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CityRunner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CityRunner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = (os.environ.get('DATABASE_URL') or '').strip()


def build_safe_database_url(raw_url):
    if not raw_url:
        return None

    normalized = raw_url.strip().replace('postgres://', 'postgresql://', 1)
    parsed = urlparse(normalized)

    username = quote(unquote(parsed.username or ''), safe='')
    password = quote(unquote(parsed.password or ''), safe='')
    hostname = parsed.hostname or ''
    port = f':{parsed.port}' if parsed.port else ''
    path = parsed.path or ''
    query = parsed.query or ''

    if query and 'sslmode=' not in query:
        query = f"{query}&sslmode=require"
    elif not query:
        query = 'sslmode=require'

    netloc = hostname
    if username:
        netloc = f'{username}@{hostname}'
    if password:
        netloc = f'{username}:{password}@{hostname}'
    if username and password:
        netloc = f'{username}:{password}@{hostname}'

    netloc = f'{netloc}{port}'
    return urlunparse((parsed.scheme, netloc, path, query, parsed.fragment))


if DATABASE_URL:
    try:
        safe_url = build_safe_database_url(DATABASE_URL)
        parsed_url = dj_database_url.parse(safe_url)
        if parsed_url.get('ENGINE') and parsed_url.get('NAME'):
            DATABASES = {'default': parsed_url}
        else:
            raise ValueError('URL de banco inválida')
    except Exception:
        DATABASES = {
            'default': dj_database_url.config(
                default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
                conn_max_age=600,
                ssl_require=False,
            )
        }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
            conn_max_age=600,
            ssl_require=False,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
