# Generated by Django 6.0.7 on 2026-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localInicio', models.CharField(max_length=100)),
                ('localFim', models.CharField(max_length=100)),
                ('distancia', models.FloatField()),
                ('descricao', models.TextField()),
            ],
        ),
    ]
