# Generated by Django 6.0.7 on 2026-07-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='avaliacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ComentariosCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.FloatField(default=0.0)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corridas.corrida')),
            ],
        ),
        migrations.AddField(
            model_name='corrida',
            name='comentarios',
            field=models.ManyToManyField(blank=True, related_name='corridas', to='corridas.comentarioscorrida'),
        ),
    ]
