# Generated by Django 6.0.7 on 2026-07-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0002_corrida_avaliacao_comentarioscorrida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrida',
            name='comentarios',
        ),
        migrations.RenameField(
            model_name='corrida',
            old_name='localFim',
            new_name='local_fim',
        ),
        migrations.RenameField(
            model_name='corrida',
            old_name='localInicio',
            new_name='local_inicio',
        ),
        migrations.CreateModel(
            name='ComentarioCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.FloatField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='corridas.corrida')),
            ],
        ),
        migrations.DeleteModel(
            name='ComentariosCorrida',
        ),
    ]
