# Generated by Django 6.0.7 on 2026-07-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0003_remove_corrida_comentarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corrida',
            name='avaliacao',
        ),
    ]
