# Generated by Django 6.0.7 on 2026-07-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0004_remove_corrida_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='destino_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='destino_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='origem_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='origem_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
