# Generated by Django 6.0.7 on 2026-07-22 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0005_corrida_destino_latitude_corrida_destino_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rankingPaceCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.FloatField()),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='corridas.corrida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='corridas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='corridas.comentariocorrida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='corridas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='corridas.corrida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas', to='corridas.usuario')),
            ],
        ),
    ]
