# Generated by Django 6.0.7 on 2026-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0006_usuario_rankingpacecorrida_usuariocomentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
